### ISSUE TITLE
2.1.0 파일을 다운받았는데 2.0.1이라고 뜨네요

### ISSUE THREAD

**Issue by Leavesss** [augustapple/ThanosCleaner#10]
2.1.0을 다운받고 exe 파일을 실행하니  2.0.1 버전을 업데이트 하라면서 404 오류가 뜨는 2.1.0 다운링크로 이동됩니다
https://github.com/augustapple/ThanosCleaner/releases/2.1.0

그리고  exe파일이 41447kb 였는데 실행하고 업데이트도 했더니 33메가바이트로 줄어들었습니다. 업데이트를 거치면 exe파일의 용량이 줄어드는 게 맞나요?

**Comment by L4by** [comment]
https://github.com/augustapple/ThanosCleaner/commit/21a4454953245a169cac102b3e2aa16778f6665f 커밋에서 수정되었습니다.
