### ISSUE TITLE
게시글이나 댓글 몇 개가 삭제된 뒤부터 작동이 정지됩니다.

### ISSUE THREAD

**Issue by juyoung9909** [augustapple/ThanosCleaner#11]
[thanoscleaner_2019_11_30_19_6_32.log](https://github.com/augustapple/ThanosCleaner/files/3907815/thanoscleaner_2019_11_30_19_6_32.log)
[thanoscleaner_2019_12_1_12_57_42.log](https://github.com/augustapple/ThanosCleaner/files/3907816/thanoscleaner_2019_12_1_12_57_42.log)

그리고 한번 삭제 처리가 멈춘 이후로는 컴퓨터를 재부팅하지 않는 한 재로그인을 반복하든 클리너를 재실행하든 관계 없이 계속 진행되지 않는 채로 있네요. 왜 이럴까요...?

**Comment by L4by** [comment]
> 현재 ThanosCleaner는 디시의 삭제 과정 reCAPTCHA 도입으로 슬로우 모드 사용을 권장하고 있습니다. (2019/11/23 기준)
>
> 슬로우 모드를 체크하지 않고 사용하시면 reCAPTCHA를 수동으로 해제해주고 다시 클리너를 돌리셔야 하니
>
> 반드시 슬로우 모드를 체크해주시기 바랍니다.

디시인사이드의 reCAPTCHA 도입으로 현재 모든 클리너가 정상적으로 작동하지 않습니다. 로그로 보았을 때 reCAPTCHA 보호가 적용된 것으로 보이므로 갤로그에서 수동으로 삭제 작업을 1회 거친 후 재시도해주시기 바랍니다.
