### ISSUE TITLE
이거 슬로우모드키고 한 몇십개 지우니깐 더이상안지워지네요

### ISSUE THREAD

**Issue by nanig224** [augustapple/ThanosCleaner#13]
흠.재부팅도하고 프로그램다시켜도 먹통입니다

**Comment by MOKISAN** [comment]
저도 동일증상입니다.

**Comment by GP32** [comment]
로그를 확인해본 결과 슬로우 모드를 활성화해도 언젠가는 캡차가 만료됩니다. 일단 임시방편으로, 더 이상 글이 삭제되지 않게 되면 웹브라우저로 디시인사이드에 접속해서 갤로그에 진입, 글이나 댓글을 아무거나 하나 삭제 시도하여 직접 캡차를 다시 진행해주고 다시 클리너를 이용하시면 됩니다.
