### ISSUE TITLE
바이러스로 인해 실행 불가

### ISSUE THREAD

**Issue by jhjeong0421** [augustapple/ThanosCleaner#17]
https://www.virustotal.com/gui/file/e8813f7d588da57ebd87b6e8ca34ef2bbc2d2083a52e2cd16416b89575d32f2f/detection

![1](https://user-images.githubusercontent.com/20179497/78421813-9463e200-7695-11ea-8cae-a396d5a09281.PNG)

e8813f7d588da57ebd87b6e8ca34ef2bbc2d2083a52e2cd16416b89575d32f2f

그제까지 잘 쓰다 오늘 갑자기 윈도우 디펜더에서 계속 파일을 날려서 (실행도 안됨)
검사해보니 검출됐네요. 진짜 바이러스인지 오탐지인지는 모르겠지만요...
버젼 v3.0.0 입니다. 
카스퍼스키 설치시 잘 작동하는데, 윈도우 디펜더에서는 막고있으니 참고바랍니다.

**Comment by augustapple** [comment]
다른 곳에서 컴파일된 부트로더가 컴파일한 사용자와 다른 사용자가 만든 파일을 불러와서 실행하는
구조를 보고 트로이목마로 착각해서 잡는 것 같습니다. 현재 배포되고 있는 3.0.0 버전은 직접 컴파일한 bootloader를 이용하여 생성된 exe 파일이니 제가 생각한 원인이 맞다면 해결되었을 것 같습니다.
그리고 VirusTotal에 등재된 백신 중 ThanosCleaner를 바이러스로 탐지한 두 백신 (Zillya, Antiy-AVL) 은 사실 주류 백신도 아니거니와 오진률이 높다는 기사가 있네요.
