### ISSUE TITLE
특정 갤러리의 게시물만 삭제할 수 있게 설정 가능한가요?

### ISSUE THREAD

**Issue by rkrkfl** [augustapple/ThanosCleaner#9]
특정 갤러리의 게시물만 삭제할 수 있게 설정 가능한가요?

만약 된다면 어떻게 하면 되나요?

**Comment by augustapple** [comment]
죄송하지만 특정 갤러리 혹은 마이너 갤러리 구분 등은 아직 구현되지 않았습니다.

가능하다면 최대한 빨리 구현하도록 하겠습니다. 감사합니다.

**Comment by L4by** [comment]
Added at https://github.com/augustapple/ThanosCleaner/releases/tag/v3.0.0
